BLK-315, Azure nio blocks
nio-blocks/azure_IoT pull request #1
Opened 2018-08-15 22:29 UTC by f1401martin

2018-08-16 22:00 UTC, shadetree01010100 requested changes

2018-08-16 22:00 UTC, shadetree01010100 commented on client.py
> +                self._logger.exception("Couldn't parse body: {}".format(body))
I'm not sure about this, does the body have to be json? In AWS, at least, it can also be a plain string in which case we simply call `decode()`.
https://github.com/nio-blocks/AWS_IoT/blob/master/aws_iot_mqtt_subscribe_block.py#L45

2018-08-17 14:24 UTC, f1401martin commented on client.py
> +                self._logger.exception("Couldn't parse body: {}".format(body))
@tyoungNIO Good call, thanks

2018-08-17 15:24 UTC, shadetree01010100 approved these changes

2018-08-17 22:05 UTC, shadetree01010100 requested changes

2018-08-17 22:05 UTC, tyoungNIO commented on client.py
> +    json_decode_error = json.JSONDecodeErrorsaer
Whoops, gotta fix that typo.

2018-08-20 15:00 UTC, shadetree01010100 approved these changes

2018-08-20 15:00 UTC, merged